### ISSUE TITLE
GoGoAnime url

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/AnimeGo#17]
Which one is real?
It seems to be https://www20.gogoanimes.tv/

**Comment by HenryQuan** [comment]
https://www1.gogoanime.io/
I will try this one later

**Comment by HenryQuan** [comment]
Ahh, my ISP blocked this site... That's why I was so confused. I will try and update the UI a little bit.

**Comment by HenryQuan** [comment]
https://www.gogoanimes.tv also works

**Comment by HenryQuan** [comment]
https://www20.gogoanimes.tv/ this one

**Comment by alvis168** [comment]
can i change default domain?

**Comment by HenryQuan** [comment]
When version are you using? For the lastest one, you cannot because it will always be up to date. Is there any reason why you want to change the default domain? I can add it back.

**Comment by alvis168** [comment]
so what version that i can change the domain?i want to change domain because i want to see anime with sub indonesia,could i have the source project that i can change the domain?

**Comment by HenryQuan** [comment]
If you go to release and download version 1.1.0, you can go to settings and update the domain name. However, I don't know if it works with other sites. For version 1.2.0, it doesn't support it yet. If you want to source code, you can use the master branch or react-native. If you search for gogoanime, I think you can find the domain and change it.

**Comment by HenryQuan** [comment]
> so what version that i can change the domain?i want to change domain because i want to see anime with sub indonesia,could i have the source project that i can change the domain?

I have implemented this in the latest version. It will be possible to change the domain in the next update.

**Comment by alvis168** [comment]
so went the next update?or can you help me how to scrape anime from website
and display to aplication?
Pada tanggal 22 Jun 2020 20:17, "Yiheng" <notifications@github.com> menulis:

**Comment by HenryQuan** [comment]
@alvis168 it will update soon. 
If you want to scrape anime from website, you need to parse the html or use some kind of APIs. Always use API whenever possible but for this app, I simply parsed the html as a model and presented it with UI.
Can you send me the link of the site? This app only works for gogoanime website and it won't work for any other site. 

** I am actually learning Indonesian at the moment. Still really beginner but at least I know menulis is write.

**Comment by alvis168** [comment]
i think the website that i want to scrape doesn't have API, riie.jp that
the website that i want to scrape. i hope you can help me to make anime app
with that website,
Pada tanggal 23 Jun 2020 07:27, "Yiheng" <notifications@github.com> menulis:

**Comment by HenryQuan** [comment]
I have checked that website. It is possible to scrape it but I don't think I will write an app for it. However, you can use the source code of this app as a base and build an app on top of it. You need to update links and parsers to work with that website. It shouldn't be that difficult because they put links in the html. I had to use a little bit of their hidden API for this app.

Also, don't forget that the issue section should only be used to report issues relating to this app. This is always a bit off topic.

**Comment by alvis168** [comment]
i have done scrape that site,but i dont know how to show video that site to
app,and how to parse that site?
Pada tanggal 23 Jun 2020 09:34, "Yiheng" <notifications@github.com> menulis:

**Comment by HenryQuan** [comment]
If you read my source code, you will see that I simply use a webview to play the video. It is not ideal and ideally, you want to get the video link from the website somehow. This is really off topic because this issue is about the domain for gogoanime so I will lock it now.
